server:
  port: 8888
  servlet:
    context-path: /writer-demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/writer1?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 8
